version: "3.8"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
    - MYSQL_DATABASE=project
    - MYSQL_USER=bacit
    - MYSQL_PASSWORD=BACIT2020
    - MYSQL_HOST=db
    ports:
    - "8081:80"
    volumes:
    - .:/var/www
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=BSBACIT2020
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=BACIT2020
    - MYSQL_DATABASE=project
   
volumes:
  mysql_data: { driver: local }
